# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27ec62891882b30e4f1cd8de1b8d7a16722c7107513cbae80a68569a2b81dc5121d50894c6452b67aa4a8306ff2c21672812d84ff7028bc541e8f1aba66c4cb8

test:
  secret_key_base: 088c4383d1933cecf18fa8796dd6e8b2890346819f08b0d5e51c5747207c2bb924e75e80b9f55c03722d9031e42399e95f4538c811bba03abe525b4ba6e46712

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
